# Generated by Django 6.1 on 2026-08-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='equipment name')),
                ('description', models.CharField(max_length=500, verbose_name='equipment description')),
                ('category', models.CharField(max_length=100, verbose_name='equipment category')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='equipment price')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='equipment deposit')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='businesses.rentalbusiness', verbose_name='rental business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='serial number')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('RENTED', 'Rented'), ('INSPECTION', 'Inspection'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='unit status')),
                ('condition', models.CharField(default='GOOD', max_length=100, verbose_name='current condition')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('notes', models.TextField(blank=True, verbose_name='unit notes')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='equipment.equipment', verbose_name='equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
