# Generated by Django 6.1 on 2026-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='business name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='business description')),
                ('location', models.CharField(max_length=300, verbose_name='business location')),
                ('phone', models.CharField(max_length=10, verbose_name='business number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
