# Generated by Django 6.1 on 2026-08-14 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBusiness',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.timestampedmodel')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='business name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='business description')),
                ('location', models.CharField(max_length=300, verbose_name='business location')),
                ('phone', models.CharField(max_length=10, verbose_name='business number')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_business', to=settings.AUTH_USER_MODEL, verbose_name='business owner')),
            ],
            bases=('users.timestampedmodel',),
        ),
    ]
